name: aes
channels:
        - conda-forge
        - bioconda
        - defaults
        - R
dependencies:
        - r-base=4.1
        - r-devtools
        - r-tidyverse=1.3.1
        - r-vegan
        - r-corncob
        - r-ggpubr
        - r-ggthemes
        - r-kableExtra
        - r-captioner
        - r-flextable
        - r-ggtext
        - bioconductor-phyloseq
        - bioconductor-dada2
        - bioconductor-decontam
        - bioconductor-ancombc
        - bioconductor-aldex2
