---
title: "Artificial Ecosystem Selection: Methane Oxidation"
author: "Andrew Morris"
output:
  html_document:
      toc: true
      toc_float: 
        collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,  fig.align="center")
library(tidyverse)
library(knitr)
library(kableExtra)
library(broom)
library(modelr)
library(lubridate)
library(morris)
library(magrittr)
```

### Standard Curve

```{r sc_data, fig.height=3}

sc <- read.csv('../Data/standard_curve.csv')

sc %>% 
  filter(molecule == 'ch4') %>% 
ggplot(mapping = aes(area, injection_ppm)) +
  facet_wrap(~ flux_date + molecule, scales = "free") + 
  geom_point() +
  stat_smooth(method = 'lm', se = FALSE)

sc_model <- function(df) {lm(injection_ppm ~ area, data = df)}
standard_curves <- 
  sc %>% 
  filter(molecule == 'ch4') %>% 
  group_by(flux_date) %>% 
  nest() %>% 
  mutate(model = map(data, sc_model),
         glance = map(model, glance),
         tidy = map(model, tidy)) 
sc_r2 <- 
  standard_curves %>% 
  unnest(glance) %>% 
  select(flux_date, r.squared)
sc_equation <- 
  standard_curves %>% 
  unnest(tidy) %>%
  select(flux_date, term, estimate) %>% 
  spread(term, estimate) %>% 
  rename(intercept = `(Intercept)`, slope = area)
sc_ch4 <- left_join(sc_r2, sc_equation, by = c("flux_date"))
sc_ch4 %>% 
  kable() %>% 
  kable_styling()

```

### Flux Measurements

```{r time_data}

time_data <- data.table::fread('../Data/time_data.csv')

time_data[, c('t0', 't1', 't2', 't3', 't4', 't5')] <- 
  lapply(time_data[, c('t0', 't1', 't2', 't3', 't4', 't5')],
         ymd_hms)

as.days <- function(start, end) {as.numeric(interval(start, end))/60/60/24}

time_data[, c('t1', 't2', 't3', 't4', 't5')] <- 
  lapply(time_data[, c('t1', 't2', 't3', 't4', 't5')],
         function(x) as.days(time_data$t1, x))
time_data <- 
 time_data %>% 
  select(-t0) %>% 
  gather(t, days, t1:t5) %>% 
  mutate(flux_date = factor(flux_date))

```




```{r}

conc_data <- data.table::fread('../Data/conc_data.csv')


conc_data <- 
  conc_data %>% 
  filter(molecule == 'ch4') %>% 
  mutate(flux_date = factor(flux_date)) %>% 
  gather(t, area, t1:t5) %>% 
  left_join(sc_ch4, by = c('flux_date')) %>% 
  mutate(ppm = area * slope + intercept) %>% 
  select(flux_date, jar, t, ppm) %>% 
  spread(t, ppm)

ln_ch0_chn <- function(t0, tn) {
  log(t0/tn)
}

conc_data[, c('t1', 't2', 't3', 't4', 't5')] <- 
  lapply(conc_data[, c('t1', 't2', 't3', 't4', 't5')],
         function(x) ln_ch0_chn(conc_data$t1, x))
flux_data <-
conc_data %>% 
  gather(t, ppm, t1:t5) %>% 
  left_join(time_data, by = c('flux_date', 'jar', 't'))


flux_data <- 
  flux_data %>% 
  mutate(flux_date = factor(ymd(flux_date)), 
         jar = factor(jar),
         t = factor(t)) %>% 
  mutate(rep = factor(substr(jar, 2, 3)),
         treat = factor(substr(jar, 1, 1)))

```

# Flux

```{r flux_curves, warning = FALSE, fig.height=8}

flux_data %>% 
  ggplot(aes(days, ppm)) + 
  facet_grid(flux_date + treat ~ rep, scales = "free") +
  geom_point() + 
  stat_smooth(method = 'lm')

```


# Fluxes

```{r flux_model}
lin_model <- function(dt) {
  lm(ppm ~ days, data = dt)
}

nested <- 
flux_data %>% 
  group_by(flux_date, jar, treat, rep) %>% 
  nest() %>% 
  mutate(model = map(data, lin_model))

fluxes <-
  nested %>% 
  mutate(tidy = map(model, tidy)) %>% 
  unnest(tidy) %>% 
  filter(term == 'days') %>% 
  group_by(flux_date) %>% 
  arrange(estimate, .by_group = TRUE) %>% 
  select(-data, -model, -term) %>% 
  ungroup() %>% 
  mutate(passage = as.numeric(flux_date)) %>% 
  mutate(estimate_rank = rank(estimate))

write_tsv(fluxes, '../Output/fluxes.tsv')

```

```{r plot_estimates}
ggplot(fluxes, aes(x = estimate, fill = treat)) +
  facet_wrap(~ flux_date, scales = "free") +
  geom_histogram(position = 'identity', alpha = 0.5, bins = 20)

ggplot(fluxes, aes(y = estimate, x = treat, color = treat)) +
  facet_wrap(~ flux_date, scales = "free") +
  geom_boxplot(outlier.shape = NA) +
  geom_label(aes(label = rep))
```




```{r test_response}

fluxes$passage <- as.numeric(fluxes$flux_date)

fit <- lm(estimate ~ treat * passage, data = fluxes)
summary(fit)
plot(fit$residuals ~ fluxes$estimate)
selection_table <- tidy(anova(fit))


selection_table[1, 1] <- "Treatment"
selection_table[2, 1] <- "Passage"
selection_table[3, 1] <- "Treatment:Passage"
selection_table[4, 1] <- "Residuals"

selection_table %>% 
  kable(col.names = c('Term', 'Df', 'Sum Sq', 'Mean Sq', 'F Value', 'p-value')) %>% 
  kable_styling()

```



```{r plot_selection_data, eval=FALSE, include=FALSE}


fluxes %>% 
  ggplot(fluxes, mapping = aes(x = passage, y = estimate, group = passage)) +
  geom_boxplot() +
  geom_jitter(width = 0.2) +
  labs(x = "Passage Number", y = "Methane Oxidation Rate (-k)") +
  theme_bw()

fluxes %>% 
  ggplot(mapping = aes(x = treat, y = estimate)) +
  geom_boxplot() +
  geom_jitter(width = 0.2) +
  labs(x = "Treatment", y = "Methane Oxidation Rate (-k)") +
  theme_bw()

library(rstanarm)

post1 <- stan_glm(estimate ~ treat, data = fluxes, prior = cauchy(), seed = 12345)
post2 <- update(post1, formula = . ~ passage)
post3 <- update(post1, formula = . ~ treat + passage)
(post4 <- update(post1, formula = . ~ treat * passage))

base <-  ggplot(fluxes, mapping = aes(x = passage, y = estimate, group = passage)) +
  geom_boxplot() +
  geom_jitter(width = 0.2) +
  labs(x = "Passage Number", y = "Methane Oxidation Rate (-k)") +
  theme_bw()
  
base + geom_abline(intercept = coef(post1)[1], slope = coef(post1)[2], 
                   color = "skyblue4", size = 1)
draws <- as.data.frame(post1)
colnames(draws)[1:2] <- c("a", "b")

base + 
  geom_abline(data = draws, aes(intercept = a, slope = b), 
              color = "skyblue", size = 0.2, alpha = 0.25) + 
  geom_abline(intercept = coef(post1)[1], slope = coef(post1)[2], 
              color = "skyblue4", size = 1)

draws <- as.data.frame(as.matrix(post2))
colnames(draws)[1:2] <- c("a", "b")
ggplot(fluxes, mapping = aes(x = treat, y = estimate)) +
  geom_boxplot() +
  geom_jitter(width = 0.2) +
  labs(x = "Treatment", y = "Methane Oxidation Rate (-k)") +
  theme_bw() +
  geom_abline(data = draws, aes(intercept = a, slope = b), 
              color = "skyblue", size = 0.2, alpha = 0.25) + 
  geom_abline(intercept = coef(post2)[1], slope = coef(post2)[2], 
              color = "skyblue4", size = 1)

reg0 <- function(x, ests) cbind(1, 0, x) %*% ests 
reg1 <- function(x, ests) cbind(1, 1, x) %*% ests

args <- list(ests = coef(post3))
lgnd <- guide_legend(title = NULL)
base2 <- ggplot(fluxes, aes(x = passage, fill = treat)) + 
  geom_jitter(aes(y = estimate), shape = 21, stroke = .2, size = 1) + 
  guides(color = lgnd, fill = lgnd) + 
  theme(legend.position = "right")
base2 + 
  stat_function(fun = reg0, args = args, aes(color = "Neutral"), size = 1.5) +
  stat_function(fun = reg1, args = args, aes(color = "Positive"), size = 1.5)

reg0 <- function(x, ests) cbind(1, 0, x, 0 * x) %*% ests 
reg1 <- function(x, ests) cbind(1, 1, x, 1 * x) %*% ests
args <- list(ests = coef(post4))
base2 +
  stat_function(fun = reg0, args = args, aes(color = "Neutral"), size = 1.5) + 
  stat_function(fun = reg1, args = args, aes(color = "Positive"), size = 1.5)

loo1 <- loo(post1, cores = 2, k_threshold = 0.7)
loo2 <- loo(post2, cores = 2, k_threshold = 0.7)
loo3 <- loo(post3, cores = 2, k_threshold = 0.7)
loo4 <- loo(post4, cores = 2, k_threshold = 0.7)
(comp <- loo_compare(loo1, loo2, loo3, loo4))
######################


post2 <- stan_lmer(estimate ~ 1 + (1|treat) + (1|passage) + (1|treat:passage),
                   data = fluxes, prior_intercept = cauchy(),
                   prior_covariance = decov(shape = 2, scale = 2),
                   adapt_delta = 0.999, seed = 12345)


```


```{r selection}

fluxes %>% 
  ggplot(mapping = aes(x = passage, y = estimate, color = treat)) +
  geom_jitter(width = 0.2) +
  #geom_smooth(method = 'lm') +
  labs(x = "Passage Number", y = "Methane Oxidation Rate (-k)") +
  scale_color_discrete(name = "Selection Treatment", labels = c('Neutral', 'Positive')) +
  theme_bw() + 
  geom_boxplot(aes(x = passage, y = estimate, color = treat, group = interaction(treat, passage)))

#ggsave('selection.pdf', width = 6, height = 4)
```

```{r selection_log_plot}

log_fluxes <- fluxes
#log_fluxes$estimate[log_fluxes$estimate < 0] <- 0.01
log_fluxes$estimate <- log10(log_fluxes$estimate + abs(min(log_fluxes$estimate)) + 0.01)

fit <- lm(estimate ~ treat * passage, data = log_fluxes)
summary(fit)
plot(fit$residuals ~ log_fluxes$estimate)

selection_table <- tidy(anova(fit))

#selection_table[1, 1] <- "Neutral0"
#selection_table[2, 1] <- "Positive0"
#selection_table[3, 1] <- "Passage#"
#selection_table[4, 1] <- "Positive:Passage#"


selection_table[1, 1] <- "Treatment"
selection_table[2, 1] <- "Passage"
selection_table[3, 1] <- "Treatment:Passage"
selection_table[4, 1] <- "Residuals"

selection_table %>% 
  kable(col.names = c('Term', 'Df', 'Sum Sq', 'Mean Sq', 'F Value', 'p-value')) %>% 
  kable_styling()


log_fluxes %>% 
  ggplot(mapping = aes(x = passage, y = estimate, color = treat)) +
  geom_jitter(width = 0.2) +
  geom_smooth(method = 'lm') +
  labs(x = "Passage Number", y = "log10(Methane Oxidation Rate (-k))") +
  scale_color_discrete(name = "Selection Treatment", labels = c('Neutral', 'Positive')) +
  theme_bw() +
  scale_y_log10()

#ggsave('selection.pdf', width = 6, height = 4)

log_fluxes %>% 
  ggplot(mapping = aes(x = passage, y = estimate, color = treat)) +
  geom_jitter(width = 0.2) +
  #geom_smooth(method = 'lm') +
  labs(x = "Passage Number", y = "Methane Oxidation Rate (-k)") +
  scale_color_discrete(name = "Selection Treatment", labels = c('Neutral', 'Positive')) +
  theme_bw() + 
  geom_boxplot(aes(x = passage, y = estimate, color = treat, group = interaction(treat, passage)))
```

```{r test_response_rank}

fluxes$estimate_rank <- rank(fluxes$estimate)
rank_fit <- lm(estimate_rank ~ treat * passage, data = fluxes)

rank_fit
summary(rank_fit)
anova(rank_fit)

plot(fit$residuals ~ fluxes$estimate_rank)

```

```{r}
selection_table <- tidy(anova(rank_fit))
selection_table[1, 1] <- "Treatment"
selection_table[2, 1] <- "Passage"
selection_table[3, 1] <- "Treatment:Passage"
selection_table[4, 1] <- "Residuals"
selection_table %>% 
  kable(col.names = c('Term', 'Df', 'Sum Sq', 'Mean Sq', 'F Value', 'p-value')) %>% 
  kable_styling()

selection_table <- tidy(car::Anova(rank_fit, type = "II"))
selection_table[1, 1] <- "Treatment"
selection_table[2, 1] <- "Passage"
selection_table[3, 1] <- "Treatment:Passage"
selection_table[4, 1] <- "Residuals"
selection_table %>% 
  kable(col.names = c('Term', 'Sum Sq', 'Df', 'F Value', 'p-value')) %>% 
  kable_styling()

selection_table <- tidy(car::Anova(rank_fit, type = "III"))
selection_table[1, 1] <- "Intercept"
selection_table[2, 1] <- "Treatment"
selection_table[3, 1] <- "Passage"
selection_table[4, 1] <- "Treatment:Passage"
selection_table[5, 1] <- "Residuals"
selection_table %>% 
  kable(col.names = c('Term', 'Sum Sq', 'Df', 'F Value', 'p-value')) %>% 
  kable_styling()

selection_table <- tidy(summary(rank_fit))

selection_table[1, 1] <- "Neutral"
selection_table[2, 1] <- "Positive"
selection_table[3, 1] <- "Passage"
selection_table[4, 1] <- "Positive:Passage"

selection_table %>% 
  kable(col.names = c('Term', 'Estimate', 'Std Error', 't-statistic', 'p-value')) %>% 
  kable_styling()

```



```{r selection_rank}

fluxes %>% 
  ggplot(mapping = aes(x = passage, y = estimate_rank, color = treat)) +
  geom_jitter(width = 0.2) +
  geom_smooth(method = 'lm') +
  labs(x = "Passage Number", y = "Rank Methane Oxidation Rate (-k)") +
  scale_color_discrete(name = "Selection Treatment", labels = c('Neutral', 'Positive')) +
  theme_bw()

ggsave('selection.pdf', width = 6, height = 4)
ggsave('selection.png', width = 6, height = 4)
```


```{r}

gm_mean = function(x, na.rm=TRUE){
  exp(sum(log(x[x > 0]), na.rm=na.rm) / length(x))
}

ggplot(fluxes, aes(x = estimate)) + 
  facet_wrap(~ passage + treat) +
  geom_dotplot(method = 'histodot') +
  geom_vline(aes(xintercept = mean(estimate)), color = 'blue') +
  geom_vline(aes(xintercept = median(estimate)), color = 'red') +
    geom_vline(aes(xintercept = gm_mean(estimate)), color = 'green')


```


# Deviance from mean

```{r}
deviance_se <- 
  fluxes %>% 
  select(treat, passage, estimate) %>% 
  group_by(passage, treat) %>% 
  summarize(se = se(estimate)) %>% 
  pivot_wider(names_from = treat, values_from = se) %>% 
  mutate(deviance_se = p + n) %>% 
  pull(deviance_se)
  

deviance <-
fluxes %>% 
  select(treat, passage, estimate) %>% 
  group_by(passage, treat) %>% 
  summarize(mean = median(estimate)) %>% 
  pivot_wider(names_from = treat, values_from = mean) %>% 
  mutate(deviance = p - n)

deviance$se <- deviance_se



fit <- lm(deviance ~ passage, data = deviance)
summary(fit)

fit <- rma(deviance~passage,se^2,method="FE",data = deviance)
fit

summary(fit)
plot(fit)

ggplot(deviance, aes(x = passage, y = deviance, ymin = deviance - se, ymax = deviance + se)) + 
  geom_pointrange() + 
  geom_abline(intercept = fit$beta[1], slope = fit$beta[2], color = 'blue')

```


# Heritability

```{r heritability, message=FALSE, warning=FALSE}
selected_jars <- read_csv('../Data/selected.csv')

parental <- 
  fluxes[paste0(fluxes$passage, fluxes$jar) %in% paste0(selected_jars$passage, selected_jars$jar), ] %>% 
  ungroup() %>% 
  select(treat, rep, estimate, passage)

parental <-
  parental %>% 
  group_by(passage, treat) %>% 
  summarize(parental = mean(estimate)) %>% 
  ungroup() %>% 
  filter(passage != 5)

offspring <- 
  fluxes %>% 
  ungroup() %>%
  select(treat, rep, estimate, passage)

ggplot(offspring, aes(x = estimate, fill = factor(passage))) +
  geom_histogram(position = "identity", alpha = 0.5)

offspring <-
  offspring %>% 
  group_by(passage, treat) %>%
  summarize(offspring = mean(estimate)) %>%
  ungroup() %>%
  # mutate(offspring = estimate) %>%
  filter(passage != 1) %>% 
  mutate(passage = passage - 1)

ggplot(heritability, aes(x = offspring)) +
  geom_histogram(position = 'identity', alpha = 0.5)

ggplot(heritability, aes(x = parental)) +
  geom_histogram(position = 'identity', alpha = 0.5)

# offspring <-
#   fluxes %>%
#   ungroup() %>%
#   select(estimate, passage, treat) %>%
#   mutate(offspring = rank(estimate))

heritability <- left_join(parental, offspring, by = c("passage", "treat"))
heritability$passage <- factor(heritability$passage)
heritability$treat <- factor(heritability$treat)
# heritability$parental <- rank(heritability$parental)

write_tsv(heritability, '../Output/heritability.tsv')

ggplot(heritability, aes(x = parental, y = offspring)) +
  geom_point(aes(color = treat)) +
  stat_smooth(method = 'lm') + 
  labs(x = "Parental Median Flux (-k)", y = "Offspring Flux (-k)") +
  scale_color_discrete(name = "Selection\nTreatment", labels = c('Neutral', 'Positive')) +
  theme_bw()

ggsave('heritability.pdf', width = 4, height = 3)
ggsave('heritability.png', width = 4, height = 3)
heritability$parental_sq <- heritability$parental^2
fit <- lm(sqrt(offspring) ~ parental, data = heritability)

summary(fit)
tidy(fit) %>% 
  kable() %>% 
  kable_styling()
glance(fit) %>% 
  kable() %>% 
  kable_styling()
ggplot(mapping = aes(fit$residuals, fit$fitted.values)) +
  geom_point()
ggplot(mapping = aes(fit$residuals, heritability$parental)) +
  geom_point()


ggplot(heritability, aes(x = parental, y = offspring)) +
  geom_point()

```

```{r}
library(rstan)

srr_block <- "
data { 
    int<lower=1> N;               // Number of observations
    int<lower=1> nX;               // Number of predictors
    matrix [N,nX] X;
    vector[N] y;                  // Methane flux values
}
parameters {
    vector[nX] beta;
    real<lower=0> sigma;
}
transformed parameters {
  vector[N] mu;
  mu = X*beta;
  }
model {
    y ~ cauchy(mu, sigma);
    sigma ~ normal(0, 0.1);
}"

Xmat <- model.matrix(~parental, heritability)
data.list <- with(heritability, list(y = offspring, X = Xmat, nX = ncol(Xmat), N = nrow(heritability)))

data.rstan <- stan(model_code = srr_block,
                            data = data.list, 
                            iter=3e3)

stan_trace(data.rstan)

mcmc = as.data.frame(data.rstan) %>% dplyr:::select(contains("beta"),
                                                    sigma) %>% as.matrix
## get median parameter estimates
coefs = apply(mcmc[, 1:2], 2, median)
fit = as.vector(coefs %*% t(Xmat))
resid = heritability$offspring - fit
ggplot() + geom_point(data = NULL, aes(y = resid, x = fit))
newdata = heritability %>% cbind(fit, resid)
ggplot(newdata) + geom_point(aes(y = resid, x = parental))


print(data.rstan, par = c("beta", "sigma"))

tidyMCMC(data.rstan, conf.int = TRUE, conf.method = "HPDinterval", pars = c("beta", "sigma"))

library(bayesplot)
posterior <- as.matrix(data.rstan)

plot_title <- ggtitle("Posterior distributions",
                      "with medians and 80% intervals")
mcmc_areas(posterior,
           pars = c("beta[2]"),
           prob = 0.8) + plot_title
```

